<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Shruti Mohanty, 705494615">

<title>Biostat 203B Homework 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="hw2_files/libs/clipboard/clipboard.min.js"></script>
<script src="hw2_files/libs/quarto-html/quarto.js"></script>
<script src="hw2_files/libs/quarto-html/popper.min.js"></script>
<script src="hw2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hw2_files/libs/quarto-html/anchor.min.js"></script>
<link href="hw2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hw2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hw2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hw2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hw2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table" id="toc-q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table" class="nav-link active" data-scroll-target="#q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table"><span class="toc-section-number">1</span>  Q1. <code>read.csv</code> (base R) vs <code>read_csv</code> (tidyverse) vs <code>fread</code> (data.table)</a></li>
  <li><a href="#q2.-icu-stays" id="toc-q2.-icu-stays" class="nav-link" data-scroll-target="#q2.-icu-stays"><span class="toc-section-number">2</span>  Q2. ICU stays</a></li>
  <li><a href="#q3.-admission-data" id="toc-q3.-admission-data" class="nav-link" data-scroll-target="#q3.-admission-data"><span class="toc-section-number">3</span>  Q3. <code>admission</code> data</a></li>
  <li><a href="#q4.-patients-data" id="toc-q4.-patients-data" class="nav-link" data-scroll-target="#q4.-patients-data"><span class="toc-section-number">4</span>  Q4. <code>patients</code> data</a></li>
  <li><a href="#q5.-lab-results" id="toc-q5.-lab-results" class="nav-link" data-scroll-target="#q5.-lab-results"><span class="toc-section-number">5</span>  Q5. Lab results</a></li>
  <li><a href="#q6.-vitals-from-charted-events" id="toc-q6.-vitals-from-charted-events" class="nav-link" data-scroll-target="#q6.-vitals-from-charted-events"><span class="toc-section-number">6</span>  Q6. Vitals from charted events</a></li>
  <li><a href="#q7.-putting-things-together" id="toc-q7.-putting-things-together" class="nav-link" data-scroll-target="#q7.-putting-things-together"><span class="toc-section-number">7</span>  Q7. Putting things together</a></li>
  <li><a href="#q8.-exploratory-data-analysis-eda" id="toc-q8.-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#q8.-exploratory-data-analysis-eda"><span class="toc-section-number">8</span>  Q8. Exploratory data analysis (EDA)</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biostat 203B Homework 2</h1>
<p class="subtitle lead">Due Feb 15 @ 11:59PM</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Shruti Mohanty, 705494615 </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>Display machine information for reproducibility:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.3.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] digest_0.6.31     lifecycle_1.0.3   jsonlite_1.8.4    magrittr_2.0.2   
 [5] evaluate_0.20     rlang_1.0.6       stringi_1.7.12    cli_3.6.0        
 [9] rstudioapi_0.14   vctrs_0.5.1       rmarkdown_2.19    tools_4.2.2      
[13] stringr_1.5.0     glue_1.6.2        htmlwidgets_1.6.1 xfun_0.36        
[17] yaml_2.3.6        fastmap_1.1.0     compiler_4.2.2    htmltools_0.5.4  
[21] knitr_1.41       </code></pre>
</div>
</div>
<p>Load necessary libraries (you can add more as needed).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(R.utils)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>MIMIC data location</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mimic_path <span class="ot">&lt;-</span> <span class="st">"~/mimic"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this exercise, we use tidyverse (ggplot2, dplyr, etc) to explore the <a href="https://mimic.mit.edu/docs/iv/">MIMIC-IV</a> data introduced in <a href="https://ucla-biostat-203b.github.io/2023winter/hw/hw1/hw1.html">homework 1</a> and to build a cohort of ICU stays.</p>
<p>Display the contents of MIMIC data folder.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(<span class="fu">str_c</span>(<span class="st">"ls -l "</span>, mimic_path, <span class="st">"/"</span>), <span class="at">intern =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "total 32"                                                                                                                  
 [2] "-rwxr-xr-x@  1 shruti  staff  2518 Mar 10  2021 LICENSE.txt"                                                               
 [3] "drwxr-xr-x   5 shruti  staff   160 Jan 23 12:57 MIMIC-reduce-chartevents"                                                  
 [4] "lrwxr-xr-x   1 shruti  staff    26 Feb 23 20:59 MIMIC_FOLDER -&gt; /PATH/TO/YOUR/MIMIC_FOLDER"                                
 [5] "-rwxr-xr-x@  1 shruti  staff  2459 Mar 16  2021 SHA256SUMS.txt"                                                            
 [6] "-rw-r--r--@  1 shruti  staff  2356 Feb 23 20:55 biostat-203b-2023winter-3fdc2392ac39.json"                                 
 [7] "drwxr-xr-x   6 shruti  staff   192 Jan 23 12:57 core"                                                                      
 [8] "drwxr-xr-x  21 shruti  staff   672 Jan 23 12:57 hosp"                                                                      
 [9] "drwxr-xr-x  11 shruti  staff   352 Jan 23 12:57 icu"                                                                       
[10] "-rwxr-xr-x@  1 shruti  staff   797 Jan  4  2022 index.html"                                                                
[11] "lrwxr-xr-x   1 shruti  staff    58 Feb 23 20:59 mimic-iv-1.0 -&gt; /Users/shruti/Desktop/Winter_2023Courses/203B/mimic-iv-1.0"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(<span class="fu">str_c</span>(<span class="st">"ls -l "</span>, mimic_path, <span class="st">"/core"</span>), <span class="at">intern =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "total 142944"                                                        
[2] "-rwxr-xr-x@ 1 shruti  staff  17208966 Mar 15  2021 admissions.csv.gz"
[3] "-rwxr-xr-x@ 1 shruti  staff       606 Jan  4  2022 index.html"       
[4] "-rwxr-xr-x@ 1 shruti  staff   2955582 Mar 15  2021 patients.csv.gz"  
[5] "-rwxr-xr-x@ 1 shruti  staff  53014503 Mar 15  2021 transfers.csv.gz" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(<span class="fu">str_c</span>(<span class="st">"ls -l "</span>, mimic_path, <span class="st">"/hosp"</span>), <span class="at">intern =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "total 9243184"                                                                        
 [2] "-rwxr-xr-x@ 1 shruti  staff      430049 Mar 15  2021 d_hcpcs.csv.gz"                  
 [3] "-rwxr-xr-x@ 1 shruti  staff      863239 Mar 15  2021 d_icd_diagnoses.csv.gz"          
 [4] "-rwxr-xr-x@ 1 shruti  staff      579998 Mar 15  2021 d_icd_procedures.csv.gz"         
 [5] "-rwxr-xr-x@ 1 shruti  staff       14898 Mar 15  2021 d_labitems.csv.gz"               
 [6] "-rwxr-xr-x@ 1 shruti  staff    29531152 Mar 15  2021 diagnoses_icd.csv.gz"            
 [7] "-rwxr-xr-x@ 1 shruti  staff    11684062 Mar 15  2021 drgcodes.csv.gz"                 
 [8] "-rwxr-xr-x@ 1 shruti  staff   515763427 Mar 15  2021 emar.csv.gz"                     
 [9] "-rwxr-xr-x@ 1 shruti  staff   476252563 Mar 15  2021 emar_detail.csv.gz"              
[10] "-rwxr-xr-x@ 1 shruti  staff     2098831 Mar 15  2021 hcpcsevents.csv.gz"              
[11] "-rwxr-xr-x@ 1 shruti  staff        2325 Jan  4  2022 index.html"                      
[12] "-rwxr-xr-x@ 1 shruti  staff  2091865786 Mar 15  2021 labevents.csv.gz"                
[13] "-rwxr-xr-x@ 1 shruti  staff   171624288 Jan 27  2022 labevents_filtered_itemid.csv.gz"
[14] "-rwxr-xr-x@ 1 shruti  staff    99133381 Mar 15  2021 microbiologyevents.csv.gz"       
[15] "-rwxr-xr-x@ 1 shruti  staff   422874088 Mar 15  2021 pharmacy.csv.gz"                 
[16] "-rwxr-xr-x@ 1 shruti  staff   501381155 Mar 15  2021 poe.csv.gz"                      
[17] "-rwxr-xr-x@ 1 shruti  staff    24020923 Mar 15  2021 poe_detail.csv.gz"               
[18] "-rwxr-xr-x@ 1 shruti  staff   367041717 Mar 15  2021 prescriptions.csv.gz"            
[19] "-rwxr-xr-x@ 1 shruti  staff     7750325 Mar 15  2021 procedures_icd.csv.gz"           
[20] "-rwxr-xr-x@ 1 shruti  staff     9565293 Mar 15  2021 services.csv.gz"                 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(<span class="fu">str_c</span>(<span class="st">"ls -l "</span>, mimic_path, <span class="st">"/icu"</span>), <span class="at">intern =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "total 5698008"                                                                          
 [2] "-rwxr-xr-x@ 1 shruti  staff  2350783547 Mar 15  2021 chartevents.csv.gz"                
 [3] "-rwxr-xr-x@ 1 shruti  staff   110272408 Jan 27  2022 chartevents_filtered_itemid.csv.gz"
 [4] "-rwxr-xr-x@ 1 shruti  staff       55917 Mar 15  2021 d_items.csv.gz"                    
 [5] "-rwxr-xr-x@ 1 shruti  staff    43296273 Mar 15  2021 datetimeevents.csv.gz"             
 [6] "-rwxr-xr-x@ 1 shruti  staff     2848628 Mar 15  2021 icustays.csv.gz"                   
 [7] "-rwxr-xr-x@ 1 shruti  staff        1103 Jan  4  2022 index.html"                        
 [8] "-rwxr-xr-x@ 1 shruti  staff   352443512 Mar 15  2021 inputevents.csv.gz"                
 [9] "-rwxr-xr-x@ 1 shruti  staff    37095672 Mar 15  2021 outputevents.csv.gz"               
[10] "-rwxr-xr-x@ 1 shruti  staff    20567368 Mar 15  2021 procedureevents.csv.gz"            </code></pre>
</div>
</div>
<section id="q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="q1.-read.csv-base-r-vs-read_csv-tidyverse-vs-fread-data.table"><span class="header-section-number">1</span> Q1. <code>read.csv</code> (base R) vs <code>read_csv</code> (tidyverse) vs <code>fread</code> (data.table)</h2>
<p>There are quite a few utilities in R for reading plain text data files. Let us test the speed of reading a moderate sized compressed csv file, <code>admissions.csv.gz</code>, by three programs: <code>read.csv</code> in base R, <code>read_csv</code> in tidyverse, and <code>fread</code> in the popular data.table package.</p>
<p>Which function is fastest? Is there difference in the (default) parsed data types? (Hint: R function <code>system.time</code> measures run times.)</p>
<p><strong>Solution :</strong> From the run times below we see that the function <code>fread</code> is the fastest, and <code>read.csv</code> is the slowest. system.time was used to measure the execution speed of these commands.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system.time</span>(adm_base <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">str_c</span>(mimic_path,<span class="st">"/core/admissions.csv.gz"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   user  system elapsed 
  5.226   0.079   5.327 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system.time</span>(adm_tidy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">str_c</span>(mimic_path,<span class="st">"/core/admissions.csv.gz"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   user  system elapsed 
  1.458   0.892   0.790 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system.time</span>(adm_table <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="fu">str_c</span>(mimic_path,<span class="st">"/core/admissions.csv.gz"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   user  system elapsed 
  0.470   0.148   0.656 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(adm_base)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   523740 obs. of  15 variables:
 $ subject_id          : int  14679932 15585972 11989120 17817079 15078341 19124609 17301855 17991012 16865435 13693648 ...
 $ hadm_id             : int  21038362 24941086 21965160 24709883 23272159 20517215 29732723 24298836 23216961 21640725 ...
 $ admittime           : chr  "2139-09-26 14:16:00" "2123-10-07 23:56:00" "2147-01-14 09:00:00" "2165-12-27 17:33:00" ...
 $ dischtime           : chr  "2139-09-28 11:30:00" "2123-10-12 11:22:00" "2147-01-17 14:25:00" "2165-12-31 21:18:00" ...
 $ deathtime           : chr  "" "" "" "" ...
 $ admission_type      : chr  "ELECTIVE" "ELECTIVE" "ELECTIVE" "ELECTIVE" ...
 $ admission_location  : chr  "" "" "" "" ...
 $ discharge_location  : chr  "HOME" "HOME" "HOME" "HOME" ...
 $ insurance           : chr  "Other" "Other" "Other" "Other" ...
 $ language            : chr  "ENGLISH" "ENGLISH" "ENGLISH" "ENGLISH" ...
 $ marital_status      : chr  "SINGLE" "" "" "" ...
 $ ethnicity           : chr  "UNKNOWN" "WHITE" "UNKNOWN" "OTHER" ...
 $ edregtime           : chr  "" "" "" "" ...
 $ edouttime           : chr  "" "" "" "" ...
 $ hospital_expire_flag: int  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(adm_tidy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [523,740 × 15] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ subject_id          : num [1:523740] 14679932 15585972 11989120 17817079 15078341 ...
 $ hadm_id             : num [1:523740] 21038362 24941086 21965160 24709883 23272159 ...
 $ admittime           : POSIXct[1:523740], format: "2139-09-26 14:16:00" "2123-10-07 23:56:00" ...
 $ dischtime           : POSIXct[1:523740], format: "2139-09-28 11:30:00" "2123-10-12 11:22:00" ...
 $ deathtime           : POSIXct[1:523740], format: NA NA ...
 $ admission_type      : chr [1:523740] "ELECTIVE" "ELECTIVE" "ELECTIVE" "ELECTIVE" ...
 $ admission_location  : chr [1:523740] NA NA NA NA ...
 $ discharge_location  : chr [1:523740] "HOME" "HOME" "HOME" "HOME" ...
 $ insurance           : chr [1:523740] "Other" "Other" "Other" "Other" ...
 $ language            : chr [1:523740] "ENGLISH" "ENGLISH" "ENGLISH" "ENGLISH" ...
 $ marital_status      : chr [1:523740] "SINGLE" NA NA NA ...
 $ ethnicity           : chr [1:523740] "UNKNOWN" "WHITE" "UNKNOWN" "OTHER" ...
 $ edregtime           : POSIXct[1:523740], format: NA NA ...
 $ edouttime           : POSIXct[1:523740], format: NA NA ...
 $ hospital_expire_flag: num [1:523740] 0 0 0 0 0 0 0 0 0 0 ...
 - attr(*, "spec")=
  .. cols(
  ..   subject_id = col_double(),
  ..   hadm_id = col_double(),
  ..   admittime = col_datetime(format = ""),
  ..   dischtime = col_datetime(format = ""),
  ..   deathtime = col_datetime(format = ""),
  ..   admission_type = col_character(),
  ..   admission_location = col_character(),
  ..   discharge_location = col_character(),
  ..   insurance = col_character(),
  ..   language = col_character(),
  ..   marital_status = col_character(),
  ..   ethnicity = col_character(),
  ..   edregtime = col_datetime(format = ""),
  ..   edouttime = col_datetime(format = ""),
  ..   hospital_expire_flag = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(adm_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'data.table' and 'data.frame':  523740 obs. of  15 variables:
 $ subject_id          : int  14679932 15585972 11989120 17817079 15078341 19124609 17301855 17991012 16865435 13693648 ...
 $ hadm_id             : int  21038362 24941086 21965160 24709883 23272159 20517215 29732723 24298836 23216961 21640725 ...
 $ admittime           : POSIXct, format: "2139-09-26 14:16:00" "2123-10-07 23:56:00" ...
 $ dischtime           : POSIXct, format: "2139-09-28 11:30:00" "2123-10-12 11:22:00" ...
 $ deathtime           : POSIXct, format: NA NA ...
 $ admission_type      : chr  "ELECTIVE" "ELECTIVE" "ELECTIVE" "ELECTIVE" ...
 $ admission_location  : chr  "" "" "" "" ...
 $ discharge_location  : chr  "HOME" "HOME" "HOME" "HOME" ...
 $ insurance           : chr  "Other" "Other" "Other" "Other" ...
 $ language            : chr  "ENGLISH" "ENGLISH" "ENGLISH" "ENGLISH" ...
 $ marital_status      : chr  "SINGLE" "" "" "" ...
 $ ethnicity           : chr  "UNKNOWN" "WHITE" "UNKNOWN" "OTHER" ...
 $ edregtime           : POSIXct, format: NA NA ...
 $ edouttime           : POSIXct, format: NA NA ...
 $ hospital_expire_flag: int  0 0 0 0 0 0 0 0 0 0 ...
 - attr(*, ".internal.selfref")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<p><code>str</code> was used to compare their datatypes. In the default parsed data types there are some differences. We can see in read.csv and fread, it reads some of the columns like subject_id as int, but read_csv read it as numeric. time was read as col_datetime in read_csv, and as POSIXct in read.csv and fread.</p>
<p>For later questions, we stick to the <code>read_csv</code> in tidyverse.</p>
</section>
<section id="q2.-icu-stays" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="q2.-icu-stays"><span class="header-section-number">2</span> Q2. ICU stays</h2>
<p><code>icustays.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/icu/icustays/" class="uri">https://mimic.mit.edu/docs/iv/modules/icu/icustays/</a>) contains data about Intensive Care Units (ICU) stays. The first 10 lines are</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/icustays.csv.gz"</span>), </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los"                                                    
 [2] "17867402,24528534,31793211,Trauma SICU (TSICU),Trauma SICU (TSICU),2154-03-03 04:11:00,2154-03-04 18:16:56,1.5874537037037035" 
 [3] "14435996,28960964,31983544,Trauma SICU (TSICU),Trauma SICU (TSICU),2150-06-19 17:57:00,2150-06-22 18:33:54,3.025625"           
 [4] "17609946,27385897,33183475,Trauma SICU (TSICU),Trauma SICU (TSICU),2138-02-05 18:54:00,2138-02-15 12:42:05,9.741724537037038"  
 [5] "18966770,23483021,34131444,Trauma SICU (TSICU),Trauma SICU (TSICU),2123-10-25 10:35:00,2123-10-25 18:59:47,0.35054398148148147"
 [6] "12776735,20817525,34547665,Neuro Stepdown,Neuro Stepdown,2200-07-12 00:33:00,2200-07-13 16:44:40,1.6747685185185184"           
 [7] "10215159,24283593,34569476,Trauma SICU (TSICU),Trauma SICU (TSICU),2124-09-20 15:05:29,2124-09-21 22:06:58,1.2926967592592593" 
 [8] "14489052,26516390,35056286,Trauma SICU (TSICU),Trauma SICU (TSICU),2118-10-26 10:33:56,2118-10-26 20:28:10,0.4126620370370371" 
 [9] "15914763,28906020,36909804,Trauma SICU (TSICU),Trauma SICU (TSICU),2176-12-14 12:00:00,2176-12-17 11:47:01,2.9909837962962964" 
[10] "16256226,20013290,39289362,Neuro Stepdown,Neuro Stepdown,2150-12-20 16:09:08,2150-12-21 14:58:40,0.9510648148148149"           </code></pre>
</div>
</div>
<ol type="1">
<li>Import <code>icustatys.csv.gz</code> as a tibble <code>icustays_tble</code>.</li>
</ol>
<p><strong>Solution:</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>icustays_tble <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/icustays.csv.gz"</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(icustays_tble,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 8
   subject_id  hadm_id  stay_id first_careunit       last_…¹ intime             
        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;                &lt;chr&gt;   &lt;dttm&gt;             
 1   17867402 24528534 31793211 Trauma SICU (TSICU)  Trauma… 2154-03-03 04:11:00
 2   14435996 28960964 31983544 Trauma SICU (TSICU)  Trauma… 2150-06-19 17:57:00
 3   17609946 27385897 33183475 Trauma SICU (TSICU)  Trauma… 2138-02-05 18:54:00
 4   18966770 23483021 34131444 Trauma SICU (TSICU)  Trauma… 2123-10-25 10:35:00
 5   12776735 20817525 34547665 Neuro Stepdown       Neuro … 2200-07-12 00:33:00
 6   10215159 24283593 34569476 Trauma SICU (TSICU)  Trauma… 2124-09-20 15:05:29
 7   14489052 26516390 35056286 Trauma SICU (TSICU)  Trauma… 2118-10-26 10:33:56
 8   15914763 28906020 36909804 Trauma SICU (TSICU)  Trauma… 2176-12-14 12:00:00
 9   16256226 20013290 39289362 Neuro Stepdown       Neuro … 2150-12-20 16:09:08
10   19194449 21641999 39387567 Coronary Care Unit … Corona… 2123-11-12 02:53:35
# … with 2 more variables: outtime &lt;dttm&gt;, los &lt;dbl&gt;, and abbreviated variable
#   name ¹​last_careunit</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>How many unique <code>subject_id</code>? Can a <code>subject_id</code> have multiple ICU stays?</li>
</ol>
<p><strong>Solution :</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(<span class="fu">distinct</span>(icustays_tble, subject_id))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 53150</code></pre>
</div>
</div>
<p>The number of unique subject_ids are 53150, but the total number of rows are 76540. So, there are subject_ids who would have had multiple ICU stays.</p>
<ol start="3" type="1">
<li>Summarize the number of ICU stays per <code>subject_id</code> by graphs.</li>
</ol>
<p><strong>Solution :</strong> For this question I have formed a tibble with subject_id and the respective count of ICU stays. I have then plotted a graph which will say how many subject_ids have stayed in the ICU for a specific period. Example how many have spent a day , or 2 days in the ICU.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>icustays_tble_summ <span class="ot">&lt;-</span> icustays_tble <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject_id) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(icustays_tble_summ,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   subject_id count
        &lt;dbl&gt; &lt;int&gt;
 1   10000032     1
 2   10000980     1
 3   10001217     2
 4   10001725     1
 5   10001884     1
 6   10002013     1
 7   10002155     3
 8   10002223     1
 9   10002348     1
10   10002428     4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the graph</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(icustays_tble_summ, <span class="fu">aes</span>(<span class="at">x =</span> count, <span class="at">y =</span> <span class="fu">after_stat</span>(count))) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"count"</span>) <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Number of ICU Stays"</span>) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Number of IDs"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<ol start="4" type="1">
<li>For each <code>subject_id</code>, let’s only keep the first ICU stay in the tibble <code>icustays_tble</code>. (Hint: <code>slice_min</code> and <code>slice_max</code> may take long. Think alternative ways to achieve the same function.)</li>
</ol>
<p><strong>Solution:</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>icustays_tble <span class="ot">&lt;-</span> icustays_tble <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject_id) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(intime, <span class="at">.by_group =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,150 × 8
   subject_id  hadm_id  stay_id first_careunit                                  
        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;                                           
 1   10000032 29079034 39553978 Medical Intensive Care Unit (MICU)              
 2   10000980 26913865 39765666 Medical Intensive Care Unit (MICU)              
 3   10001217 24597018 37067082 Surgical Intensive Care Unit (SICU)             
 4   10001725 25563031 31205490 Medical/Surgical Intensive Care Unit (MICU/SICU)
 5   10001884 26184834 37510196 Medical Intensive Care Unit (MICU)              
 6   10002013 23581541 39060235 Cardiac Vascular Intensive Care Unit (CVICU)    
 7   10002155 23822395 33685454 Coronary Care Unit (CCU)                        
 8   10002223 22494570 39638202 Trauma SICU (TSICU)                             
 9   10002348 22725460 32610785 Neuro Intermediate                              
10   10002428 28662225 33987268 Medical Intensive Care Unit (MICU)              
   last_careunit                                    intime             
   &lt;chr&gt;                                            &lt;dttm&gt;             
 1 Medical Intensive Care Unit (MICU)               2180-07-23 14:00:00
 2 Medical Intensive Care Unit (MICU)               2189-06-27 08:42:00
 3 Surgical Intensive Care Unit (SICU)              2157-11-20 19:18:02
 4 Medical/Surgical Intensive Care Unit (MICU/SICU) 2110-04-11 15:52:22
 5 Medical Intensive Care Unit (MICU)               2131-01-11 04:20:05
 6 Cardiac Vascular Intensive Care Unit (CVICU)     2160-05-18 10:00:53
 7 Coronary Care Unit (CCU)                         2129-08-04 12:45:00
 8 Trauma SICU (TSICU)                              2158-01-15 08:01:49
 9 Neuro Intermediate                               2112-11-30 23:24:00
10 Medical Intensive Care Unit (MICU)               2156-04-12 16:24:18
   outtime               los
   &lt;dttm&gt;              &lt;dbl&gt;
 1 2180-07-23 23:50:47 0.410
 2 2189-06-27 20:38:27 0.498
 3 2157-11-21 22:08:00 1.12 
 4 2110-04-12 23:59:56 1.34 
 5 2131-01-20 08:27:30 9.17 
 6 2160-05-19 17:33:33 1.31 
 7 2129-08-10 17:02:38 6.18 
 8 2158-01-16 15:19:24 1.30 
 9 2112-12-10 18:25:13 9.79 
10 2156-04-17 15:57:08 4.98 
# … with 53,140 more rows</code></pre>
</div>
</div>
</section>
<section id="q3.-admission-data" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="q3.-admission-data"><span class="header-section-number">3</span> Q3. <code>admission</code> data</h2>
<p>Information of the patients admitted into hospital is available in <code>admissions.csv.gz</code>. See <a href="https://mimic.mit.edu/docs/iv/modules/hosp/admissions/" class="uri">https://mimic.mit.edu/docs/iv/modules/hosp/admissions/</a> for details of each field in this file. The first 10 lines are</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/core/admissions.csv.gz"</span>), </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,marital_status,ethnicity,edregtime,edouttime,hospital_expire_flag"
 [2] "14679932,21038362,2139-09-26 14:16:00,2139-09-28 11:30:00,,ELECTIVE,,HOME,Other,ENGLISH,SINGLE,UNKNOWN,,,0"                                                                                
 [3] "15585972,24941086,2123-10-07 23:56:00,2123-10-12 11:22:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0"                                                                                        
 [4] "11989120,21965160,2147-01-14 09:00:00,2147-01-17 14:25:00,,ELECTIVE,,HOME,Other,ENGLISH,,UNKNOWN,,,0"                                                                                      
 [5] "17817079,24709883,2165-12-27 17:33:00,2165-12-31 21:18:00,,ELECTIVE,,HOME,Other,ENGLISH,,OTHER,,,0"                                                                                        
 [6] "15078341,23272159,2122-08-28 08:48:00,2122-08-30 12:32:00,,ELECTIVE,,HOME,Other,ENGLISH,,BLACK/AFRICAN AMERICAN,,,0"                                                                       
 [7] "19124609,20517215,2169-03-14 12:44:00,2169-03-20 19:15:00,,ELECTIVE,,HOME,Other,ENGLISH,,UNKNOWN,,,0"                                                                                      
 [8] "17301855,29732723,2140-06-06 14:23:00,2140-06-08 14:25:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0"                                                                                        
 [9] "17991012,24298836,2181-07-10 20:28:00,2181-07-12 15:49:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0"                                                                                        
[10] "16865435,23216961,2185-07-19 02:12:00,2185-07-21 11:50:00,,ELECTIVE,,HOME,Other,ENGLISH,,WHITE,,,0"                                                                                        </code></pre>
</div>
</div>
<ol type="1">
<li>Import <code>admissions.csv.gz</code> as a tibble <code>admissions_tble</code>.</li>
</ol>
<p><strong>Solution :</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>admissions_tble <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">str_c</span>(mimic_path, <span class="st">"/core/admissions.csv.gz"</span>))</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(admissions_tble,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 15
   subject…¹ hadm_id admittime           dischtime           deathtime
       &lt;dbl&gt;   &lt;dbl&gt; &lt;dttm&gt;              &lt;dttm&gt;              &lt;dttm&gt;   
 1  14679932  2.10e7 2139-09-26 14:16:00 2139-09-28 11:30:00 NA       
 2  15585972  2.49e7 2123-10-07 23:56:00 2123-10-12 11:22:00 NA       
 3  11989120  2.20e7 2147-01-14 09:00:00 2147-01-17 14:25:00 NA       
 4  17817079  2.47e7 2165-12-27 17:33:00 2165-12-31 21:18:00 NA       
 5  15078341  2.33e7 2122-08-28 08:48:00 2122-08-30 12:32:00 NA       
 6  19124609  2.05e7 2169-03-14 12:44:00 2169-03-20 19:15:00 NA       
 7  17301855  2.97e7 2140-06-06 14:23:00 2140-06-08 14:25:00 NA       
 8  17991012  2.43e7 2181-07-10 20:28:00 2181-07-12 15:49:00 NA       
 9  16865435  2.32e7 2185-07-19 02:12:00 2185-07-21 11:50:00 NA       
10  13693648  2.16e7 2111-01-30 23:43:00 2111-02-02 13:03:00 NA       
# … with 10 more variables: admission_type &lt;chr&gt;, admission_location &lt;chr&gt;,
#   discharge_location &lt;chr&gt;, insurance &lt;chr&gt;, language &lt;chr&gt;,
#   marital_status &lt;chr&gt;, ethnicity &lt;chr&gt;, edregtime &lt;dttm&gt;, edouttime &lt;dttm&gt;,
#   hospital_expire_flag &lt;dbl&gt;, and abbreviated variable name ¹​subject_id</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Let’s only keep the admissions that have a match in <code>icustays_tble</code> according to <code>subject_id</code> and <code>hadmi_id</code>.</li>
</ol>
<p><strong>Solution :</strong> Using semi-join, we can keep the rows in the <code>admissions_tble</code> with the same <code>subject_id</code> and <code>hadmi_id</code> as in <code>icustays_tble</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>admissions_tble <span class="ot">&lt;-</span> admissions_tble <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(<span class="fu">select</span>(icustays_tble, subject_id, hadm_id), </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"subject_id"</span>, <span class="st">"hadm_id"</span>))  <span class="sc">%&gt;%</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,150 × 15
   subject_id  hadm_id admittime           dischtime          
        &lt;dbl&gt;    &lt;dbl&gt; &lt;dttm&gt;              &lt;dttm&gt;             
 1   10222255 28200985 2120-11-20 20:25:00 2120-11-22 13:00:00
 2   14485852 28712010 2113-10-31 00:23:00 2113-11-04 16:50:00
 3   18709254 23758948 2195-10-12 01:31:00 2195-10-12 13:51:00
 4   16837807 23526268 2151-03-19 06:09:00 2151-03-19 07:20:00
 5   17642680 27734285 2116-05-29 12:48:00 2116-05-30 12:31:00
 6   18230965 21251728 2142-03-12 20:00:00 2142-03-17 15:26:00
 7   17374121 27667114 2115-07-22 07:15:00 2115-07-24 17:50:00
 8   13346506 28533404 2181-11-19 14:32:00 2181-11-22 18:47:00
 9   18030332 24679656 2152-07-22 21:28:00 2152-07-27 16:49:00
10   14328744 29576470 2126-08-20 09:26:00 2126-08-21 11:36:00
   deathtime           admission_type     admission_location    
   &lt;dttm&gt;              &lt;chr&gt;              &lt;chr&gt;                 
 1 NA                  EU OBSERVATION     TRANSFER FROM HOSPITAL
 2 NA                  EW EMER.           EMERGENCY ROOM        
 3 NA                  EU OBSERVATION     EMERGENCY ROOM        
 4 2151-03-19 07:20:00 EU OBSERVATION     EMERGENCY ROOM        
 5 NA                  EU OBSERVATION     WALK-IN/SELF REFERRAL 
 6 NA                  URGENT             PHYSICIAN REFERRAL    
 7 NA                  DIRECT OBSERVATION PHYSICIAN REFERRAL    
 8 NA                  EU OBSERVATION     EMERGENCY ROOM        
 9 NA                  URGENT             TRANSFER FROM HOSPITAL
10 NA                  EU OBSERVATION     EMERGENCY ROOM        
   discharge_location insurance language marital_status ethnicity
   &lt;chr&gt;              &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;          &lt;chr&gt;    
 1 &lt;NA&gt;               Other     ENGLISH  MARRIED        WHITE    
 2 &lt;NA&gt;               Other     ENGLISH  SINGLE         WHITE    
 3 &lt;NA&gt;               Medicaid  ENGLISH  WIDOWED        ASIAN    
 4 &lt;NA&gt;               Medicare  ENGLISH  SINGLE         WHITE    
 5 &lt;NA&gt;               Other     ENGLISH  SINGLE         WHITE    
 6 HOME               Other     ENGLISH  MARRIED        WHITE    
 7 &lt;NA&gt;               Other     ENGLISH  MARRIED        WHITE    
 8 &lt;NA&gt;               Other     ENGLISH  MARRIED        WHITE    
 9 HOME               Other     ENGLISH  MARRIED        UNKNOWN  
10 &lt;NA&gt;               Other     ENGLISH  MARRIED        WHITE    
   edregtime           edouttime           hospital_expire_flag
   &lt;dttm&gt;              &lt;dttm&gt;                             &lt;dbl&gt;
 1 2120-11-20 18:07:00 2120-11-21 20:25:00                    0
 2 2113-10-30 19:48:00 2113-10-31 05:10:00                    0
 3 2195-10-11 18:40:00 2195-10-12 02:47:00                    0
 4 2151-03-19 02:55:00 2151-03-19 06:59:00                    1
 5 2116-05-29 10:05:00 2116-05-30 01:17:00                    0
 6 NA                  NA                                     0
 7 NA                  NA                                     0
 8 2181-11-19 10:51:00 2181-11-19 15:12:00                    0
 9 NA                  NA                                     0
10 2126-08-19 23:01:00 2126-08-20 10:14:00                    0
# … with 53,140 more rows</code></pre>
</div>
</div>
<ol start="3" type="1">
<li><p>Summarize the following variables by graphics.</p>
<ul>
<li>admission year<br>
</li>
<li>admission month<br>
</li>
<li>admission month day<br>
</li>
<li>admission week day<br>
</li>
<li>admission hour (anything unusual?)<br>
</li>
<li>admission minute (anything unusual?)<br>
</li>
<li>length of hospital stay (anything unusual?)</li>
</ul></li>
</ol>
<p><strong>Solution:</strong> Bar plots have been used to summarize these variables</p>
<pre><code>- admission year</code></pre>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> admissions_tble) <span class="sc">+</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">year</span>(admittime))) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Admission year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<pre><code>- admission month  </code></pre>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> admissions_tble) <span class="sc">+</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_count</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> lubridate<span class="sc">::</span><span class="fu">month</span>(admittime, <span class="at">label =</span> <span class="cn">TRUE</span>))) <span class="sc">+</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Admission month"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<pre><code>- admission month day  </code></pre>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> admissions_tble) <span class="sc">+</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_count</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">mday</span>(admittime))) <span class="sc">+</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Admission month day"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<pre><code>- admission week day  </code></pre>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> admissions_tble) <span class="sc">+</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_count</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> lubridate<span class="sc">::</span><span class="fu">wday</span>(admittime, <span class="at">label =</span> <span class="cn">TRUE</span>))) <span class="sc">+</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Admission week day"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<pre><code>- admission hour (anything unusual?)  
From the plot below it can be seen that the frequency is the highest at midnight and early morning at 7am maybe when the hospital opens.   </code></pre>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> admissions_tble) <span class="sc">+</span> </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_count</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">hour</span>(admittime))) <span class="sc">+</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Admission hour"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<pre><code>- admission minute (anything unusual?)  - Its unusual that the admit time is the highest in the start of every hour and is gradually decreasing with peaks every 15 mins. This also might have something to do with the hospital rules. </code></pre>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> admissions_tble) <span class="sc">+</span> </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_count</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">minute</span>(admittime))) <span class="sc">+</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Admission Minute"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<pre><code>- length of hospital stay (anything unusual?)   </code></pre>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>patients <span class="ot">&lt;-</span> admissions_tble <span class="sc">%&gt;%</span> </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">length_of_stay =</span> <span class="fu">difftime</span>(dischtime, admittime, <span class="at">units =</span> <span class="st">"days"</span>))</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>stay_freq <span class="ot">&lt;-</span> patients <span class="sc">%&gt;%</span> </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(length_of_stay) <span class="sc">%&gt;%</span> </span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(stay_freq, <span class="fu">aes</span>(<span class="at">x =</span> length_of_stay, <span class="at">y =</span> n)) <span class="sc">+</span> </span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Length of Stay (Days)"</span>) <span class="sc">+</span></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Number of Patients"</span>) <span class="sc">+</span></span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Length of Stay Distribution"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="q4.-patients-data" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="q4.-patients-data"><span class="header-section-number">4</span> Q4. <code>patients</code> data</h2>
<p>Patient information is available in <code>patients.csv.gz</code>. See <a href="https://mimic.mit.edu/docs/iv/modules/hosp/patients/" class="uri">https://mimic.mit.edu/docs/iv/modules/hosp/patients/</a> for details of each field in this file. The first 10 lines are</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/core/patients.csv.gz"</span>), </span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod"
 [2] "10000048,F,23,2126,2008 - 2010,"                               
 [3] "10002723,F,0,2128,2017 - 2019,"                                
 [4] "10003939,M,0,2184,2008 - 2010,"                                
 [5] "10004222,M,0,2161,2014 - 2016,"                                
 [6] "10005325,F,0,2154,2011 - 2013,"                                
 [7] "10007338,F,0,2153,2017 - 2019,"                                
 [8] "10008101,M,0,2142,2008 - 2010,"                                
 [9] "10009872,F,0,2168,2014 - 2016,"                                
[10] "10011333,F,0,2132,2014 - 2016,"                                </code></pre>
</div>
</div>
<ol type="1">
<li>Import <code>patients.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/hosp/patients/" class="uri">https://mimic.mit.edu/docs/iv/modules/hosp/patients/</a>) as a tibble <code>patients_tble</code> and only keep the patients who have a match in <code>icustays_tble</code> (according to <code>subject_id</code>).</li>
</ol>
<p><strong>Solution:</strong> It can be imported as a tibble as in previous questions and we can use a semi_join to keep the matching subject_id only.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>patients_tble <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">str_c</span>(mimic_path, <span class="st">"/core/patients.csv.gz"</span>))</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>patients_tble <span class="ot">&lt;-</span> patients_tble <span class="sc">%&gt;%</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(subject_id) <span class="sc">%&gt;%</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(icustays_tble, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"subject_id"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,150 × 6
   subject_id gender anchor_age anchor_year anchor_year_group dod       
        &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;             &lt;date&gt;    
 1   10000032 F              52        2180 2014 - 2016       NA        
 2   10000980 F              73        2186 2008 - 2010       NA        
 3   10001217 F              55        2157 2011 - 2013       NA        
 4   10001725 F              46        2110 2011 - 2013       NA        
 5   10001884 F              68        2122 2008 - 2010       2131-01-20
 6   10002013 F              53        2156 2008 - 2010       NA        
 7   10002155 F              80        2128 2008 - 2010       2131-03-10
 8   10002223 M              21        2158 2008 - 2010       NA        
 9   10002348 F              77        2112 2017 - 2019       NA        
10   10002428 F              80        2155 2011 - 2013       NA        
# … with 53,140 more rows</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Summarize variables <code>gender</code> and <code>anchor_age</code>, and explain any patterns you see.</li>
</ol>
<p><strong>Solution:</strong> The following is a plot for gender. We can see that the number of male patients is more than female patients over here.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>patients_tble<span class="sc">$</span>gender <span class="sc">%&gt;%</span> </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">gender =</span> value) <span class="sc">%&gt;%</span> </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> gender)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>The following is the bar plot for age. We can see a lot of patients of the age 91 here. Maybe the record in hospital has all patients of age 91 and older as 91, which explains the high distribution. The median age of patients admitted to the hospital is 65, and the mean is 63.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>patients_tble<span class="sc">$</span>anchor_age <span class="sc">%&gt;%</span> </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">anchor_age =</span> value) <span class="sc">%&gt;%</span> </span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> anchor_age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>patients_tble<span class="sc">$</span>anchor_age <span class="sc">%&gt;%</span> </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 63.51349</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>patients_tble<span class="sc">$</span>anchor_age <span class="sc">%&gt;%</span> </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">median</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 65</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>patients_tble<span class="sc">$</span>anchor_age <span class="sc">%&gt;%</span> </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">max</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 91</code></pre>
</div>
</div>
</section>
<section id="q5.-lab-results" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="q5.-lab-results"><span class="header-section-number">5</span> Q5. Lab results</h2>
<p><code>labevents.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/hosp/labevents/" class="uri">https://mimic.mit.edu/docs/iv/modules/hosp/labevents/</a>) contains all laboratory measurements for patients. The first 10 lines are</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/hosp/labevents.csv.gz"</span>), </span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "labevent_id,subject_id,hadm_id,specimen_id,itemid,charttime,storetime,value,valuenum,valueuom,ref_range_lower,ref_range_upper,flag,priority,comments"
 [2] "670,10000048,,6448755,51484,2126-11-22 19:20:00,2126-11-22 20:07:00,150,150,mg/dL,,,,STAT,"                                                          
 [3] "673,10000048,,6448755,51491,2126-11-22 19:20:00,2126-11-22 20:07:00,6.5,6.5,units,5,8,,STAT,"                                                        
 [4] "675,10000048,,6448755,51498,2126-11-22 19:20:00,2126-11-22 20:07:00,1.029,1.029, ,1.001,1.035,,STAT,"                                                
 [5] "683,10000048,,82729055,50861,2126-11-22 20:45:00,2126-11-23 00:55:00,39,39,IU/L,0,40,,STAT,"                                                         
 [6] "684,10000048,,82729055,50862,2126-11-22 20:45:00,2126-11-23 00:55:00,4.7,4.7,g/dL,3.4,4.8,,STAT,"                                                    
 [7] "685,10000048,,82729055,50863,2126-11-22 20:45:00,2126-11-23 00:55:00,45,45,IU/L,39,117,,STAT,"                                                       
 [8] "686,10000048,,82729055,50868,2126-11-22 20:45:00,2126-11-22 21:32:00,13,13,mEq/L,8,20,,STAT,"                                                        
 [9] "687,10000048,,82729055,50878,2126-11-22 20:45:00,2126-11-23 00:55:00,28,28,IU/L,0,40,,STAT,"                                                         
[10] "688,10000048,,82729055,50882,2126-11-22 20:45:00,2126-11-22 21:32:00,26,26,mEq/L,22,32,,STAT,"                                                       </code></pre>
</div>
</div>
<p><code>d_labitems.csv.gz</code> is the dictionary of lab measurements.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/hosp/d_labitems.csv.gz"</span>), </span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "itemid,label,fluid,category,loinc_code"           
 [2] "51905, ,Other Body Fluid,Chemistry,"              
 [3] "51532,11-Deoxycorticosterone,Blood,Chemistry,"    
 [4] "51957,17-Hydroxycorticosteroids,Urine,Chemistry," 
 [5] "51958,\"17-Ketosteroids, Urine\",Urine,Chemistry,"
 [6] "52068,24 Hr,Blood,Hematology,"                    
 [7] "51066,24 hr Calcium,Urine,Chemistry,"             
 [8] "51067,24 hr Creatinine,Urine,Chemistry,"          
 [9] "51068,24 hr Protein,Urine,Chemistry,"             
[10] "50853,25-OH Vitamin D,Blood,Chemistry,"           </code></pre>
</div>
</div>
<ol type="1">
<li>Find how many rows are in <code>labevents.csv.gz</code>.</li>
</ol>
<p><strong>Solution:</strong> The number of rows in <code>labevents.csv.gz</code> are 122103667.This takes a lot of time to render and run into HTML.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/hosp/labevents.csv.gz"</span>),</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | tail -n +2 | wc -l"</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>  ), </span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li><p>We are interested in the lab measurements of creatinine (50912), potassium (50971), sodium (50983), chloride (50902), bicarbonate (50882), hematocrit (51221), white blood cell count (51301), and glucose (50931). Retrieve a subset of <code>labevents.csv.gz</code> only containing these items for the patients in <code>icustays_tble</code> as a tibble <code>labevents_tble</code>.</p>
<p>Hint: <code>labevents.csv.gz</code> is a data file too big to be read in by the <code>read_csv</code> function in its default setting. Utilize the <code>col_select</code> option in the <code>read_csv</code> function to reduce the memory burden. It took my computer 5-10 minutes to ingest this file. If your computer really has trouble importing <code>labevents.csv.gz</code>, you can import from the reduced data file <code>labevents_filtered_itemid.csv.gz</code>.</p></li>
</ol>
<p><strong>Solution:</strong> I used a semi-join and filter here to select these lab measurements. This new tibble has 16,698,462 rows.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>lab_filter <span class="ot">=</span> </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="dv">50912</span>, <span class="dv">50971</span>, <span class="dv">50983</span>, <span class="dv">50902</span>, <span class="dv">50882</span>, <span class="dv">51221</span>, <span class="dv">51301</span>, <span class="dv">50931</span>)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>lab_items <span class="ot">=</span> </span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>((<span class="fu">str_c</span>(mimic_path, <span class="st">"/hosp/d_labitems.csv.gz"</span>)),<span class="at">col_select =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>),    <span class="at">show_col_types =</span> <span class="cn">FALSE</span> ) <span class="sc">%&gt;%</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(itemid <span class="sc">%in%</span> lab_filter)</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>labevents_tble <span class="ot">=</span> </span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>((<span class="fu">str_c</span>(mimic_path, <span class="st">"/hosp/labevents_filtered_itemid.csv.gz"</span>)), </span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(lab_items, <span class="at">by =</span> <span class="st">"itemid"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(<span class="fu">select</span>(icustays_tble, subject_id), <span class="at">by =</span> <span class="st">"subject_id"</span>) </span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a>labevents_tble <span class="sc">%&gt;%</span></span>
<span id="cb73-12"><a href="#cb73-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16,698,462 × 5
   subject_id itemid charttime           valuenum label            
        &lt;dbl&gt;  &lt;dbl&gt; &lt;dttm&gt;                 &lt;dbl&gt; &lt;chr&gt;            
 1   10003700  50882 2162-11-15 17:00:00     27   Bicarbonate      
 2   10003700  50902 2162-11-15 17:00:00    103   Chloride         
 3   10003700  50912 2162-11-15 17:00:00      1   Creatinine       
 4   10003700  50931 2162-11-15 17:00:00     93   Glucose          
 5   10003700  50971 2162-11-15 17:00:00      4.1 Potassium        
 6   10003700  50983 2162-11-15 17:00:00    141   Sodium           
 7   10003700  51221 2162-11-15 17:00:00     40   Hematocrit       
 8   10003700  51301 2162-11-15 17:00:00      6.7 White Blood Cells
 9   10003700  51221 2165-04-24 03:40:00     41   Hematocrit       
10   10003700  51301 2165-04-24 03:40:00      5.8 White Blood Cells
# … with 16,698,452 more rows</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Further restrict <code>labevents_tble</code> to the first lab measurement during the ICU stay.</li>
</ol>
<p><strong>Solution:</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>labevents_tble <span class="ot">=</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(labevents_tble, <span class="fu">select</span>(icustays_tble, subject_id, intime, outtime),</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="st">"subject_id"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(charttime <span class="sc">&lt;</span> outtime <span class="sc">&amp;</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>         charttime <span class="sc">&gt;</span> intime</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject_id, itemid) <span class="sc">%&gt;%</span></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(charttime, <span class="at">.by_group =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>intime, <span class="sc">-</span>outtime)</span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a>labevents_tble1 <span class="ot">=</span> labevents_tble</span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a>labevents_tble <span class="ot">=</span> </span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(labevents_tble, <span class="at">names_from =</span> <span class="fu">c</span>(<span class="st">"itemid"</span>, <span class="st">"label"</span>),</span>
<span id="cb75-15"><a href="#cb75-15" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> <span class="fu">c</span>(<span class="st">"charttime"</span>,<span class="st">"valuenum"</span>))</span>
<span id="cb75-16"><a href="#cb75-16" aria-hidden="true" tabindex="-1"></a>labevents_tble <span class="sc">%&gt;%</span></span>
<span id="cb75-17"><a href="#cb75-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 51,619 × 21
   subject_id charttime_50882_Bicarbonate charttime_50893_NA 
        &lt;dbl&gt; &lt;dttm&gt;                      &lt;dttm&gt;             
 1   10000032 2180-07-23 21:45:00         2180-07-23 21:45:00
 2   10001217 2157-11-21 03:16:00         2157-11-21 03:16:00
 3   10001725 2110-04-11 18:02:00         2110-04-11 18:02:00
 4   10001884 2131-01-11 06:31:00         2131-01-11 06:31:00
 5   10002013 2160-05-18 14:38:00         NA                 
 6   10002155 2129-08-04 17:56:00         2129-08-04 17:56:00
 7   10002223 2158-01-16 01:50:00         2158-01-16 01:50:00
 8   10002348 2112-12-01 06:36:00         2112-12-01 06:36:00
 9   10002428 2156-04-12 19:24:00         2156-04-12 19:24:00
10   10002430 2129-06-13 00:48:00         2129-06-13 00:48:00
   charttime_50902_Chloride charttime_50912_Creatinine charttime_50931_Glucose
   &lt;dttm&gt;                   &lt;dttm&gt;                     &lt;dttm&gt;                 
 1 2180-07-23 21:45:00      2180-07-23 21:45:00        2180-07-23 21:45:00    
 2 2157-11-21 03:16:00      2157-11-21 03:16:00        2157-11-21 03:16:00    
 3 2110-04-11 18:02:00      2110-04-11 18:02:00        2110-04-11 18:02:00    
 4 2131-01-11 06:31:00      2131-01-11 06:31:00        2131-01-11 06:31:00    
 5 2160-05-18 14:38:00      2160-05-18 14:38:00        2160-05-19 04:00:00    
 6 2129-08-04 17:56:00      2129-08-04 17:56:00        2129-08-04 17:56:00    
 7 2158-01-16 01:50:00      2158-01-16 01:50:00        2158-01-16 01:50:00    
 8 2112-12-01 06:36:00      2112-12-01 06:36:00        2112-12-01 06:36:00    
 9 2156-04-12 19:24:00      2156-04-12 19:24:00        2156-04-12 19:24:00    
10 2129-06-13 00:48:00      2129-06-13 00:48:00        2129-06-13 00:48:00    
   charttime_50960_NA  charttime_50971_Potassium charttime_50983_Sodium
   &lt;dttm&gt;              &lt;dttm&gt;                    &lt;dttm&gt;                
 1 2180-07-23 21:45:00 2180-07-23 21:45:00       2180-07-23 21:45:00   
 2 2157-11-21 03:16:00 2157-11-21 03:16:00       2157-11-21 03:16:00   
 3 2110-04-11 18:02:00 2110-04-11 18:02:00       2110-04-11 18:02:00   
 4 2131-01-11 06:31:00 2131-01-11 06:31:00       2131-01-11 06:31:00   
 5 2160-05-18 17:30:00 2160-05-18 14:38:00       2160-05-18 14:38:00   
 6 2129-08-04 17:56:00 2129-08-04 17:56:00       2129-08-04 17:56:00   
 7 2158-01-16 01:50:00 2158-01-16 01:50:00       2158-01-16 01:50:00   
 8 2112-12-01 06:36:00 2112-12-01 06:36:00       2112-12-01 06:36:00   
 9 2156-04-12 19:24:00 2156-04-12 19:24:00       2156-04-12 19:24:00   
10 2129-06-13 00:48:00 2129-06-13 00:48:00       2129-06-13 00:48:00   
   charttime_51221_Hematocrit `charttime_51301_White Blood Cells`
   &lt;dttm&gt;                     &lt;dttm&gt;                             
 1 NA                         NA                                 
 2 2157-11-21 03:16:00        2157-11-21 03:16:00                
 3 2110-04-11 18:02:00        2110-04-11 18:02:00                
 4 2131-01-11 06:31:00        2131-01-11 06:31:00                
 5 2160-05-18 13:01:00        2160-05-18 13:01:00                
 6 2129-08-04 17:56:00        2129-08-04 17:56:00                
 7 2158-01-15 13:02:00        2158-01-16 01:50:00                
 8 2112-12-01 06:36:00        2112-12-01 06:36:00                
 9 2156-04-12 19:24:00        2156-04-12 19:24:00                
10 2129-06-13 00:48:00        2129-06-13 00:48:00                
   valuenum_50882_Bicarbonate valuenum_50893_NA valuenum_50902_Chloride
                        &lt;dbl&gt;             &lt;dbl&gt;                   &lt;dbl&gt;
 1                         21               9.3                     102
 2                         23               8.2                     104
 3                         24               9.1                     106
 4                         33               9.8                      96
 5                         23              NA                       109
 6                         25               8.8                     106
 7                         26               8.7                     102
 8                         23               9.4                     107
 9                         20               7.4                      98
10                         22               9.2                     105
   valuenum_50912_Creatinine valuenum_50931_Glucose valuenum_50960_NA
                       &lt;dbl&gt;                  &lt;dbl&gt;             &lt;dbl&gt;
 1                       0.5                    115               2.3
 2                       0.4                    113               1.9
 3                       0.8                    146               1.5
 4                       1.1                    148               2.2
 5                       1.1                     98               2.1
 6                       0.9                     95               2  
 7                       0.8                     88               2  
 8                       0.8                    127               1.6
 9                       0.8                     99               1.4
10                       2.2                    128               2.3
   valuenum_50971_Potassium valuenum_50983_Sodium valuenum_51221_Hematocrit
                      &lt;dbl&gt;                 &lt;dbl&gt;                     &lt;dbl&gt;
 1                      4.7                   132                      NA  
 2                      3.6                   138                      33.6
 3                      3.9                   140                      39.1
 4                      4                     136                      36  
 5                      4                     140                      28.6
 6                      4.5                   139                      37.9
 7                      3.9                   138                      32.5
 8                      4.8                   142                      39.3
 9                      3.9                   129                      28.7
10                      3.8                   144                      36.6
   `valuenum_51301_White Blood Cells`
                                &lt;dbl&gt;
 1                               NA  
 2                               19  
 3                               17  
 4                               18.4
 5                               18.2
 6                                5.5
 7                               10.1
 8                                4.3
 9                               22.4
10                               10.3
# … with 51,609 more rows</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Summarize the lab measurements by appropriate numerics and graphics.</li>
</ol>
<p><strong>Solution:</strong> I used summary to get the numerical statistics from this tibble. From the box plot it can be seen that for id 50931 - glucose there are a lot of outliers.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(labevents_tble[<span class="sc">-</span><span class="dv">1</span>]) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> charttime_50882_Bicarbonate      charttime_50893_NA           
 Min.   :2110-01-11 13:00:00.00   Min.   :2110-01-12 01:29:00  
 1st Qu.:2132-11-09 13:07:30.00   1st Qu.:2132-12-16 03:02:30  
 Median :2152-10-03 16:06:00.00   Median :2152-10-24 18:00:00  
 Mean   :2152-10-26 09:59:18.75   Mean   :2152-11-24 00:55:47  
 3rd Qu.:2172-10-20 07:56:00.00   3rd Qu.:2172-11-06 15:55:00  
 Max.   :2211-05-01 10:54:00.00   Max.   :2211-05-01 10:54:00  
 NA's   :252                      NA's   :2804                 
 charttime_50902_Chloride         charttime_50912_Creatinine      
 Min.   :2110-01-11 13:00:00.00   Min.   :2110-01-11 13:00:00.00  
 1st Qu.:2132-11-09 06:58:45.00   1st Qu.:2132-11-10 05:32:30.00  
 Median :2152-10-03 04:24:00.00   Median :2152-10-03 16:06:00.00  
 Mean   :2152-10-25 18:53:15.85   Mean   :2152-10-26 18:21:13.82  
 3rd Qu.:2172-10-20 18:43:30.00   3rd Qu.:2172-10-20 12:30:30.00  
 Max.   :2211-05-01 10:54:00.00   Max.   :2211-05-01 10:54:00.00  
 NA's   :225                      NA's   :244                     
 charttime_50931_Glucose          charttime_50960_NA              
 Min.   :2110-01-12 01:29:00.00   Min.   :2110-01-12 01:29:00.00  
 1st Qu.:2132-11-07 06:36:00.00   1st Qu.:2132-11-29 03:32:00.00  
 Median :2152-10-03 03:11:00.00   Median :2152-10-08 03:20:00.00  
 Mean   :2152-10-24 11:12:38.01   Mean   :2152-11-06 17:21:56.89  
 3rd Qu.:2172-10-20 00:27:00.00   3rd Qu.:2172-11-04 00:39:00.00  
 Max.   :2211-05-01 10:54:00.00   Max.   :2211-05-01 10:54:00.00  
 NA's   :348                      NA's   :1332                    
 charttime_50971_Potassium        charttime_50983_Sodium          
 Min.   :2110-01-11 13:00:00.00   Min.   :2110-01-11 13:00:00.00  
 1st Qu.:2132-11-10 04:50:15.00   1st Qu.:2132-11-09 06:58:45.00  
 Median :2152-10-03 04:24:00.00   Median :2152-10-03 04:24:00.00  
 Mean   :2152-10-26 07:32:18.15   Mean   :2152-10-25 19:48:24.34  
 3rd Qu.:2172-10-20 20:18:15.00   3rd Qu.:2172-10-21 00:30:15.00  
 Max.   :2211-05-01 10:54:00.00   Max.   :2211-05-01 10:54:00.00  
 NA's   :225                      NA's   :225                     
 charttime_51221_Hematocrit       charttime_51301_White Blood Cells
 Min.   :2110-01-11 11:50:00.00   Min.   :2110-01-11 11:50:00      
 1st Qu.:2132-11-07 11:02:00.00   1st Qu.:2132-11-07 04:45:30      
 Median :2152-09-22 17:21:30.00   Median :2152-09-28 06:03:00      
 Mean   :2152-10-23 10:56:04.59   Mean   :2152-10-24 05:24:10      
 3rd Qu.:2172-10-23 18:46:15.00   3rd Qu.:2172-10-23 01:54:30      
 Max.   :2211-05-01 10:54:00.00   Max.   :2211-05-01 10:54:00      
 NA's   :303                      NA's   :448                      
 valuenum_50882_Bicarbonate valuenum_50893_NA valuenum_50902_Chloride
 Min.   : 2.00              Min.   : 0.000    Min.   : 58.0          
 1st Qu.:21.00              1st Qu.: 7.900    1st Qu.:101.0          
 Median :23.00              Median : 8.400    Median :105.0          
 Mean   :22.96              Mean   : 8.349    Mean   :104.5          
 3rd Qu.:25.00              3rd Qu.: 8.800    3rd Qu.:108.0          
 Max.   :49.00              Max.   :43.000    Max.   :153.0          
 NA's   :278                NA's   :2809      NA's   :238            
 valuenum_50912_Creatinine valuenum_50931_Glucose valuenum_50960_NA
 Min.   : 0.000            Min.   :   7.0         Min.   : 0.000   
 1st Qu.: 0.700            1st Qu.: 103.0         1st Qu.: 1.700   
 Median : 0.900            Median : 124.0         Median : 2.000   
 Mean   : 1.311            Mean   : 141.4         Mean   : 2.001   
 3rd Qu.: 1.300            3rd Qu.: 156.0         3rd Qu.: 2.200   
 Max.   :36.900            Max.   :2440.0         Max.   :47.000   
 NA's   :257               NA's   :354            NA's   :1339     
 valuenum_50971_Potassium valuenum_50983_Sodium valuenum_51221_Hematocrit
 Min.   : 0.800           Min.   : 92.0         Min.   : 4.30            
 1st Qu.: 3.700           1st Qu.:136.0         1st Qu.:28.10            
 Median : 4.100           Median :139.0         Median :32.60            
 Mean   : 4.178           Mean   :138.5         Mean   :32.74            
 3rd Qu.: 4.500           3rd Qu.:141.0         3rd Qu.:37.30            
 Max.   :13.000           Max.   :180.0         Max.   :68.60            
 NA's   :264              NA's   :232           NA's   :504              
 valuenum_51301_White Blood Cells
 Min.   :  0.00                  
 1st Qu.:  7.60                  
 Median : 10.60                  
 Mean   : 12.07                  
 3rd Qu.: 14.50                  
 Max.   :572.50                  
 NA's   :627                     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>labevents_tble1 <span class="sc">%&gt;%</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.character</span>(itemid), <span class="at">y =</span> valuenum)) <span class="co">#</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 496 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="q6.-vitals-from-charted-events" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="q6.-vitals-from-charted-events"><span class="header-section-number">6</span> Q6. Vitals from charted events</h2>
<p><code>chartevents.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/icu/chartevents/" class="uri">https://mimic.mit.edu/docs/iv/modules/icu/chartevents/</a>) contains all the charted data available for a patient. During their ICU stay, the primary repository of a patient’s information is their electronic chart. The <code>itemid</code> variable indicates a single measurement type in the database. The <code>value</code> variable is the value measured for <code>itemid</code>. The first 10 lines of <code>chartevents.csv.gz</code> are</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/chartevents.csv.gz"</span>), </span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span>), </span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "subject_id,hadm_id,stay_id,charttime,storetime,itemid,value,valuenum,valueuom,warning"
 [2] "10003700,28623837,30600691,2165-04-24 05:10:00,2165-04-24 05:11:00,228236,0,0,,0"     
 [3] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225067,0,0,,0"     
 [4] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225070,1,1,,0"     
 [5] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225076,1,1,,0"     
 [6] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225078,1,1,,0"     
 [7] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225086,1,1,,0"     
 [8] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225091,1,1,,0"     
 [9] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225103,1,1,,0"     
[10] "10003700,28623837,30600691,2165-04-24 05:12:00,2165-04-24 05:14:00,225106,1,1,,0"     </code></pre>
</div>
</div>
<p><code>d_items.csv.gz</code> (<a href="https://mimic.mit.edu/docs/iv/modules/icu/d_items/" class="uri">https://mimic.mit.edu/docs/iv/modules/icu/d_items/</a>) is the dictionary for the <code>itemid</code> in <code>chartevents.csv.gz</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_c</span>(</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcat &lt; "</span>, </span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/d_items.csv.gz"</span>), </span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">" | head"</span>), </span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">intern =</span> <span class="cn">TRUE</span></span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "itemid,label,abbreviation,linksto,category,unitname,param_type,lownormalvalue,highnormalvalue"   
 [2] "220003,ICU Admission date,ICU Admission date,datetimeevents,ADT,,Date and time,,"                
 [3] "220045,Heart Rate,HR,chartevents,Routine Vital Signs,bpm,Numeric,,"                              
 [4] "220046,Heart rate Alarm - High,HR Alarm - High,chartevents,Alarms,bpm,Numeric,,"                 
 [5] "220047,Heart Rate Alarm - Low,HR Alarm - Low,chartevents,Alarms,bpm,Numeric,,"                   
 [6] "220048,Heart Rhythm,Heart Rhythm,chartevents,Routine Vital Signs,,Text,,"                        
 [7] "220050,Arterial Blood Pressure systolic,ABPs,chartevents,Routine Vital Signs,mmHg,Numeric,90,140"
 [8] "220051,Arterial Blood Pressure diastolic,ABPd,chartevents,Routine Vital Signs,mmHg,Numeric,60,90"
 [9] "220052,Arterial Blood Pressure mean,ABPm,chartevents,Routine Vital Signs,mmHg,Numeric,,"         
[10] "220056,Arterial Blood Pressure Alarm - Low,ABP Alarm - Low,chartevents,Alarms,mmHg,Numeric,,"    </code></pre>
</div>
</div>
<ol type="1">
<li><p>We are interested in the vitals for ICU patients: heart rate (220045), mean non-invasive blood pressure (220181), systolic non-invasive blood pressure (220179), body temperature in Fahrenheit (223761), and respiratory rate (220210). Retrieve a subset of <code>chartevents.csv.gz</code> only containing these items for the patients in <code>icustays_tble</code> as a tibble <code>chartevents_tble</code>.</p>
<p>Hint: <code>chartevents.csv.gz</code> is a data file too big to be read in by the <code>read_csv</code> function in its default setting. Utilize the <code>col_select</code> option in the <code>read_csv</code> function to reduce the memory burden. It took my computer &gt;15 minutes to ingest this file. If your computer really has trouble importing <code>chartevents.csv.gz</code>, you can import from the reduced data file <code>chartevents_filtered_itemid.csv.gz</code>.</p></li>
</ol>
<p><strong>Solution :</strong> Used a mix of semi-join and filter for this.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>vital_filter <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">220045</span>, <span class="dv">220181</span>, <span class="dv">220179</span>, <span class="dv">223761</span>, <span class="dv">220210</span>)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>vit <span class="ot">=</span> </span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>((<span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/d_items.csv.gz"</span>)), </span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">col_select =</span> <span class="fu">c</span>(<span class="dv">1</span>), </span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(itemid <span class="sc">%in%</span> vital_filter)</span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>chartevents_tble <span class="ot">=</span> </span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>((<span class="fu">str_c</span>(mimic_path, <span class="st">"/icu/chartevents_filtered_itemid.csv.gz"</span>)), </span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb85-10"><a href="#cb85-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(<span class="fu">select</span>(vit, itemid), <span class="at">by =</span> <span class="st">"itemid"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb85-11"><a href="#cb85-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(<span class="fu">select</span>(icustays_tble, subject_id), <span class="at">by =</span> <span class="st">"subject_id"</span>)</span>
<span id="cb85-12"><a href="#cb85-12" aria-hidden="true" tabindex="-1"></a>chartevents_tble <span class="sc">%&gt;%</span></span>
<span id="cb85-13"><a href="#cb85-13" aria-hidden="true" tabindex="-1"></a> <span class="fu">print</span> (<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23,679,058 × 6
   subject_id  hadm_id  stay_id charttime           itemid valuenum
        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;dttm&gt;               &lt;dbl&gt;    &lt;dbl&gt;
 1   10003700 28623837 30600691 2165-04-24 05:28:00 220179    152  
 2   10003700 28623837 30600691 2165-04-24 05:28:00 220181    110  
 3   10003700 28623837 30600691 2165-04-24 05:30:00 220045     65  
 4   10003700 28623837 30600691 2165-04-24 05:30:00 220210     14  
 5   10003700 28623837 30600691 2165-04-24 05:38:00 223761     97.6
 6   10003700 28623837 30600691 2165-04-24 06:00:00 220045     56  
 7   10003700 28623837 30600691 2165-04-24 06:00:00 220179    126  
 8   10003700 28623837 30600691 2165-04-24 06:00:00 220181     88  
 9   10003700 28623837 30600691 2165-04-24 06:00:00 220210     14  
10   10003700 28623837 30600691 2165-04-24 06:09:00 220045     55  
# … with 23,679,048 more rows</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Further restrict <code>chartevents_tble</code> to the first vital measurement during the ICU stay.</li>
</ol>
<p><strong>Solution::</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>chartevents_tble_summ <span class="ot">=</span> </span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>    chartevents_tble, <span class="fu">select</span>(icustays_tble, subject_id, intime, outtime), </span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="st">"subject_id"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(charttime <span class="sc">&lt;</span> outtime <span class="sc">&amp;</span></span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>         charttime <span class="sc">&gt;</span> intime</span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span></span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject_id, itemid) <span class="sc">%&gt;%</span></span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(charttime, <span class="at">.by_group =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb87-11"><a href="#cb87-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb87-12"><a href="#cb87-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>intime, <span class="sc">-</span>outtime, <span class="sc">-</span>hadm_id, <span class="sc">-</span>stay_id)</span>
<span id="cb87-13"><a href="#cb87-13" aria-hidden="true" tabindex="-1"></a>chartevents_tble <span class="ot">=</span> </span>
<span id="cb87-14"><a href="#cb87-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb87-15"><a href="#cb87-15" aria-hidden="true" tabindex="-1"></a>    chartevents_tble_summ, <span class="at">names_prefix =</span> <span class="st">""</span>, <span class="at">names_from =</span> <span class="fu">c</span>(<span class="st">"itemid"</span>), </span>
<span id="cb87-16"><a href="#cb87-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> <span class="fu">c</span>(<span class="st">"charttime"</span>,<span class="st">"valuenum"</span>))</span>
<span id="cb87-17"><a href="#cb87-17" aria-hidden="true" tabindex="-1"></a>chartevents_tble <span class="sc">%&gt;%</span></span>
<span id="cb87-18"><a href="#cb87-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,136 × 11
   subject_id charttime_220045    charttime_220179    charttime_220181   
        &lt;dbl&gt; &lt;dttm&gt;              &lt;dttm&gt;              &lt;dttm&gt;             
 1   10000032 2180-07-23 14:12:00 2180-07-23 14:11:00 2180-07-23 14:11:00
 2   10000980 2189-06-27 08:56:00 2189-06-27 08:55:00 2189-06-27 08:55:00
 3   10001217 2157-11-20 19:19:00 2157-11-20 19:19:00 2157-11-20 19:19:00
 4   10001725 2110-04-11 15:54:00 2110-04-11 16:00:00 2110-04-11 16:00:00
 5   10001884 2131-01-11 04:22:00 2131-01-11 04:25:00 2131-01-11 04:25:00
 6   10002013 2160-05-18 14:07:00 2160-05-19 07:53:00 2160-05-19 07:53:00
 7   10002155 2129-08-04 13:45:00 2129-08-04 16:49:00 2129-08-04 16:49:00
 8   10002223 2158-01-15 08:15:00 2158-01-15 08:18:00 2158-01-15 08:18:00
 9   10002348 2112-11-30 23:43:00 2112-12-01 00:10:00 2112-12-01 00:10:00
10   10002428 2156-04-12 17:26:00 2156-04-12 17:27:00 2156-04-12 17:27:00
   charttime_220210    charttime_223761    valuenum_220045 valuenum_220179
   &lt;dttm&gt;              &lt;dttm&gt;                        &lt;dbl&gt;           &lt;dbl&gt;
 1 2180-07-23 14:12:00 2180-07-23 17:00:00              91              84
 2 2189-06-27 08:54:00 2189-06-27 09:07:00              77             150
 3 2157-11-20 19:19:00 2157-11-20 19:31:00              86             151
 4 2110-04-11 16:00:00 2110-04-11 20:32:00              55              73
 5 2131-01-11 05:00:00 2131-01-12 20:00:00              38             180
 6 2160-05-18 14:07:00 2160-05-19 08:00:00              80             104
 7 2129-08-04 13:45:00 2129-08-04 14:00:00              68             126
 8 2158-01-15 08:15:00 2158-01-15 12:00:00             100             123
 9 2112-11-30 23:43:00 2112-11-30 23:31:00              72             129
10 2156-04-12 17:26:00 2156-04-12 17:25:00             124              87
   valuenum_220181 valuenum_220210 valuenum_223761
             &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;
 1              56              24            98.7
 2              92              23            98  
 3             104              18            98.5
 4              59              19            97.7
 5              46              10            98.1
 6              77              14            97.2
 7              78              18            95.9
 8              80              29            98.6
 9              85              14            97.9
10              53              25           103. 
# … with 53,126 more rows</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Summarize these vital measurements by appropriate numerics and graphics.</li>
</ol>
<p><strong>Solution:</strong> The values have been summarised in numerics and graphical form.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(chartevents_tble [<span class="sc">-</span><span class="dv">1</span>]) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> charttime_220045                 charttime_220179                
 Min.   :2110-01-11 12:42:00.00   Min.   :2110-01-11 16:42:00.00  
 1st Qu.:2132-11-01 03:05:45.00   1st Qu.:2132-11-07 03:47:30.00  
 Median :2152-09-23 03:17:00.00   Median :2152-10-06 18:17:00.00  
 Mean   :2152-10-25 12:38:46.10   Mean   :2152-10-31 21:49:41.13  
 3rd Qu.:2172-10-27 22:45:00.00   3rd Qu.:2172-11-04 21:03:30.00  
 Max.   :2211-05-01 10:00:00.00   Max.   :2211-05-01 10:00:00.00  
 NA's   :2                        NA's   :670                     
 charttime_220181                 charttime_220210                
 Min.   :2110-01-11 16:42:00.00   Min.   :2110-01-11 12:42:00.00  
 1st Qu.:2132-11-07 12:08:00.00   1st Qu.:2132-10-28 22:30:30.00  
 Median :2152-10-08 03:40:00.00   Median :2152-09-24 09:17:30.00  
 Mean   :2152-11-02 11:06:49.22   Mean   :2152-10-25 18:17:15.85  
 3rd Qu.:2172-11-06 01:21:00.00   3rd Qu.:2172-10-30 06:07:30.00  
 Max.   :2211-05-01 10:00:00.00   Max.   :2211-05-01 10:00:00.00  
 NA's   :691                      NA's   :48                      
 charttime_223761                 valuenum_220045  valuenum_220179  
 Min.   :2110-01-12 05:00:00.00   Min.   :  0.00   Min.   :    0.0  
 1st Qu.:2132-10-27 14:50:00.00   1st Qu.: 74.00   1st Qu.:  106.0  
 Median :2152-09-21 02:30:00.00   Median : 85.00   Median :  122.0  
 Mean   :2152-10-26 08:45:33.46   Mean   : 87.44   Mean   :  123.8  
 3rd Qu.:2172-10-27 15:11:00.00   3rd Qu.: 99.00   3rd Qu.:  139.0  
 Max.   :2211-05-01 10:00:00.00   Max.   :941.00   Max.   :12262.0  
 NA's   :943                      NA's   :2        NA's   :670      
 valuenum_220181    valuenum_220210  valuenum_223761 
 Min.   :     0.0   Min.   :  0.00   Min.   :  0.00  
 1st Qu.:    70.0   1st Qu.: 15.00   1st Qu.: 97.60  
 Median :    81.0   Median : 18.00   Median : 98.10  
 Mean   :    87.4   Mean   : 18.69   Mean   : 98.04  
 3rd Qu.:    93.0   3rd Qu.: 22.00   3rd Qu.: 98.70  
 Max.   :140119.0   Max.   :180.00   Max.   :105.80  
 NA's   :691        NA's   :48       NA's   :943     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>chartevents_tble_summ <span class="sc">%&gt;%</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.character</span>(itemid), <span class="at">y =</span> valuenum)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="q7.-putting-things-together" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="q7.-putting-things-together"><span class="header-section-number">7</span> Q7. Putting things together</h2>
<p>Let us create a tibble <code>mimic_icu_cohort</code> for all ICU stays, where rows are the first ICU stay of each unique adult (age at admission &gt; 18) and columns contain at least following variables</p>
<ul>
<li>all variables in <code>icustays.csv.gz</code><br>
</li>
<li>all variables in <code>admission.csv.gz</code><br>
</li>
<li>all variables in <code>patients.csv.gz</code><br>
</li>
<li>first lab measurements during ICU stay<br>
</li>
<li>first vital measurements during ICU stay</li>
<li>an indicator variable <code>thirty_day_mort</code> whether the patient died within 30 days of hospital admission (30 day mortality)</li>
</ul>
<p><strong>Solution:</strong> Putting together all the tibbles in the previous question for this question. This tibble <code>mimic_icu_cohort</code> has 53065 rows, and the last column contains the TRUE or FALSE values for <code>thirty_day_mort</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>mimic_icu_cohort <span class="ot">=</span> </span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(icustays_tble, admissions_tble, </span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"subject_id"</span>, <span class="st">"hadm_id"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(patients_tble, <span class="at">by =</span> <span class="st">"subject_id"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(labevents_tble, <span class="at">by =</span> <span class="st">"subject_id"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(chartevents_tble, <span class="at">by =</span> <span class="st">"subject_id"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_hadm =</span> anchor_age <span class="sc">+</span> <span class="fu">year</span>(admittime) <span class="sc">-</span> anchor_year) <span class="sc">%&gt;%</span></span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age_hadm <span class="sc">&gt;</span> <span class="dv">18</span>) <span class="sc">%&gt;%</span></span>
<span id="cb92-9"><a href="#cb92-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">thirty_day_mort =</span> </span>
<span id="cb92-10"><a href="#cb92-10" aria-hidden="true" tabindex="-1"></a>             <span class="fu">ifelse</span>(<span class="fu">is.na</span>(deathtime), <span class="st">"FALSE"</span>, </span>
<span id="cb92-11"><a href="#cb92-11" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">ifelse</span>(<span class="fu">as.Date</span>(deathtime) <span class="sc">-</span> <span class="fu">as.Date</span>(admittime) <span class="sc">&lt;=</span> <span class="dv">30</span>, </span>
<span id="cb92-12"><a href="#cb92-12" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"TRUE"</span>, <span class="st">"FALSE"</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb92-13"><a href="#cb92-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,065 × 58
   subject_id  hadm_id  stay_id first_careunit                                  
        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;                                           
 1   10000032 29079034 39553978 Medical Intensive Care Unit (MICU)              
 2   10000980 26913865 39765666 Medical Intensive Care Unit (MICU)              
 3   10001217 24597018 37067082 Surgical Intensive Care Unit (SICU)             
 4   10001725 25563031 31205490 Medical/Surgical Intensive Care Unit (MICU/SICU)
 5   10001884 26184834 37510196 Medical Intensive Care Unit (MICU)              
 6   10002013 23581541 39060235 Cardiac Vascular Intensive Care Unit (CVICU)    
 7   10002155 23822395 33685454 Coronary Care Unit (CCU)                        
 8   10002223 22494570 39638202 Trauma SICU (TSICU)                             
 9   10002348 22725460 32610785 Neuro Intermediate                              
10   10002428 28662225 33987268 Medical Intensive Care Unit (MICU)              
   last_careunit                                    intime             
   &lt;chr&gt;                                            &lt;dttm&gt;             
 1 Medical Intensive Care Unit (MICU)               2180-07-23 14:00:00
 2 Medical Intensive Care Unit (MICU)               2189-06-27 08:42:00
 3 Surgical Intensive Care Unit (SICU)              2157-11-20 19:18:02
 4 Medical/Surgical Intensive Care Unit (MICU/SICU) 2110-04-11 15:52:22
 5 Medical Intensive Care Unit (MICU)               2131-01-11 04:20:05
 6 Cardiac Vascular Intensive Care Unit (CVICU)     2160-05-18 10:00:53
 7 Coronary Care Unit (CCU)                         2129-08-04 12:45:00
 8 Trauma SICU (TSICU)                              2158-01-15 08:01:49
 9 Neuro Intermediate                               2112-11-30 23:24:00
10 Medical Intensive Care Unit (MICU)               2156-04-12 16:24:18
   outtime               los admittime           dischtime          
   &lt;dttm&gt;              &lt;dbl&gt; &lt;dttm&gt;              &lt;dttm&gt;             
 1 2180-07-23 23:50:47 0.410 2180-07-23 12:35:00 2180-07-25 17:55:00
 2 2189-06-27 20:38:27 0.498 2189-06-27 07:38:00 2189-07-03 03:00:00
 3 2157-11-21 22:08:00 1.12  2157-11-18 22:56:00 2157-11-25 18:00:00
 4 2110-04-12 23:59:56 1.34  2110-04-11 15:08:00 2110-04-14 15:00:00
 5 2131-01-20 08:27:30 9.17  2131-01-07 20:39:00 2131-01-20 05:15:00
 6 2160-05-19 17:33:33 1.31  2160-05-18 07:45:00 2160-05-23 13:30:00
 7 2129-08-10 17:02:38 6.18  2129-08-04 12:44:00 2129-08-18 16:53:00
 8 2158-01-16 15:19:24 1.30  2158-01-15 08:00:00 2158-01-20 19:29:00
 9 2112-12-10 18:25:13 9.79  2112-11-30 22:22:00 2112-12-10 17:56:00
10 2156-04-17 15:57:08 4.98  2156-04-12 14:16:00 2156-04-29 16:26:00
   deathtime           admission_type              admission_location    
   &lt;dttm&gt;              &lt;chr&gt;                       &lt;chr&gt;                 
 1 NA                  EW EMER.                    EMERGENCY ROOM        
 2 NA                  EW EMER.                    EMERGENCY ROOM        
 3 NA                  EW EMER.                    EMERGENCY ROOM        
 4 NA                  EW EMER.                    PACU                  
 5 2131-01-20 05:15:00 OBSERVATION ADMIT           EMERGENCY ROOM        
 6 NA                  SURGICAL SAME DAY ADMISSION PHYSICIAN REFERRAL    
 7 NA                  EW EMER.                    PROCEDURE SITE        
 8 NA                  EW EMER.                    EMERGENCY ROOM        
 9 NA                  OBSERVATION ADMIT           TRANSFER FROM HOSPITAL
10 NA                  EW EMER.                    EMERGENCY ROOM        
   discharge_location           insurance language marital_status
   &lt;chr&gt;                        &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;         
 1 HOME                         Medicaid  ENGLISH  WIDOWED       
 2 HOME HEALTH CARE             Medicare  ENGLISH  MARRIED       
 3 HOME HEALTH CARE             Other     ?        MARRIED       
 4 HOME                         Other     ENGLISH  MARRIED       
 5 DIED                         Medicare  ENGLISH  MARRIED       
 6 HOME HEALTH CARE             Medicare  ENGLISH  SINGLE        
 7 CHRONIC/LONG TERM ACUTE CARE Other     ENGLISH  MARRIED       
 8 HOME                         Other     ENGLISH  &lt;NA&gt;          
 9 HOME HEALTH CARE             Medicare  ENGLISH  SINGLE        
10 SKILLED NURSING FACILITY     Medicare  ENGLISH  WIDOWED       
   ethnicity              edregtime           edouttime          
   &lt;chr&gt;                  &lt;dttm&gt;              &lt;dttm&gt;             
 1 WHITE                  2180-07-23 05:54:00 2180-07-23 14:00:00
 2 BLACK/AFRICAN AMERICAN 2189-06-27 06:25:00 2189-06-27 08:42:00
 3 WHITE                  2157-11-18 17:38:00 2157-11-19 01:24:00
 4 WHITE                  NA                  NA                 
 5 BLACK/AFRICAN AMERICAN 2131-01-07 13:36:00 2131-01-07 22:13:00
 6 OTHER                  NA                  NA                 
 7 WHITE                  2129-08-04 11:00:00 2129-08-04 12:35:00
 8 UNABLE TO OBTAIN       2158-01-15 06:49:00 2158-01-15 07:36:00
 9 WHITE                  2112-11-30 15:08:00 2112-11-30 23:24:00
10 WHITE                  2156-04-12 09:56:00 2156-04-12 17:11:00
   hospital_expire_flag gender anchor_age anchor_year anchor_year_group
                  &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;            
 1                    0 F              52        2180 2014 - 2016      
 2                    0 F              73        2186 2008 - 2010      
 3                    0 F              55        2157 2011 - 2013      
 4                    0 F              46        2110 2011 - 2013      
 5                    1 F              68        2122 2008 - 2010      
 6                    0 F              53        2156 2008 - 2010      
 7                    0 F              80        2128 2008 - 2010      
 8                    0 M              21        2158 2008 - 2010      
 9                    0 F              77        2112 2017 - 2019      
10                    0 F              80        2155 2011 - 2013      
   dod        charttime_50882_Bicarbonate charttime_50893_NA 
   &lt;date&gt;     &lt;dttm&gt;                      &lt;dttm&gt;             
 1 NA         2180-07-23 21:45:00         2180-07-23 21:45:00
 2 NA         NA                          NA                 
 3 NA         2157-11-21 03:16:00         2157-11-21 03:16:00
 4 NA         2110-04-11 18:02:00         2110-04-11 18:02:00
 5 2131-01-20 2131-01-11 06:31:00         2131-01-11 06:31:00
 6 NA         2160-05-18 14:38:00         NA                 
 7 2131-03-10 2129-08-04 17:56:00         2129-08-04 17:56:00
 8 NA         2158-01-16 01:50:00         2158-01-16 01:50:00
 9 NA         2112-12-01 06:36:00         2112-12-01 06:36:00
10 NA         2156-04-12 19:24:00         2156-04-12 19:24:00
   charttime_50902_Chloride charttime_50912_Creatinine charttime_50931_Glucose
   &lt;dttm&gt;                   &lt;dttm&gt;                     &lt;dttm&gt;                 
 1 2180-07-23 21:45:00      2180-07-23 21:45:00        2180-07-23 21:45:00    
 2 NA                       NA                         NA                     
 3 2157-11-21 03:16:00      2157-11-21 03:16:00        2157-11-21 03:16:00    
 4 2110-04-11 18:02:00      2110-04-11 18:02:00        2110-04-11 18:02:00    
 5 2131-01-11 06:31:00      2131-01-11 06:31:00        2131-01-11 06:31:00    
 6 2160-05-18 14:38:00      2160-05-18 14:38:00        2160-05-19 04:00:00    
 7 2129-08-04 17:56:00      2129-08-04 17:56:00        2129-08-04 17:56:00    
 8 2158-01-16 01:50:00      2158-01-16 01:50:00        2158-01-16 01:50:00    
 9 2112-12-01 06:36:00      2112-12-01 06:36:00        2112-12-01 06:36:00    
10 2156-04-12 19:24:00      2156-04-12 19:24:00        2156-04-12 19:24:00    
   charttime_50960_NA  charttime_50971_Potassium charttime_50983_Sodium
   &lt;dttm&gt;              &lt;dttm&gt;                    &lt;dttm&gt;                
 1 2180-07-23 21:45:00 2180-07-23 21:45:00       2180-07-23 21:45:00   
 2 NA                  NA                        NA                    
 3 2157-11-21 03:16:00 2157-11-21 03:16:00       2157-11-21 03:16:00   
 4 2110-04-11 18:02:00 2110-04-11 18:02:00       2110-04-11 18:02:00   
 5 2131-01-11 06:31:00 2131-01-11 06:31:00       2131-01-11 06:31:00   
 6 2160-05-18 17:30:00 2160-05-18 14:38:00       2160-05-18 14:38:00   
 7 2129-08-04 17:56:00 2129-08-04 17:56:00       2129-08-04 17:56:00   
 8 2158-01-16 01:50:00 2158-01-16 01:50:00       2158-01-16 01:50:00   
 9 2112-12-01 06:36:00 2112-12-01 06:36:00       2112-12-01 06:36:00   
10 2156-04-12 19:24:00 2156-04-12 19:24:00       2156-04-12 19:24:00   
   charttime_51221_Hematocrit `charttime_51301_White Blood Cells`
   &lt;dttm&gt;                     &lt;dttm&gt;                             
 1 NA                         NA                                 
 2 NA                         NA                                 
 3 2157-11-21 03:16:00        2157-11-21 03:16:00                
 4 2110-04-11 18:02:00        2110-04-11 18:02:00                
 5 2131-01-11 06:31:00        2131-01-11 06:31:00                
 6 2160-05-18 13:01:00        2160-05-18 13:01:00                
 7 2129-08-04 17:56:00        2129-08-04 17:56:00                
 8 2158-01-15 13:02:00        2158-01-16 01:50:00                
 9 2112-12-01 06:36:00        2112-12-01 06:36:00                
10 2156-04-12 19:24:00        2156-04-12 19:24:00                
   valuenum_50882_Bicarbonate valuenum_50893_NA valuenum_50902_Chloride
                        &lt;dbl&gt;             &lt;dbl&gt;                   &lt;dbl&gt;
 1                         21               9.3                     102
 2                         NA              NA                        NA
 3                         23               8.2                     104
 4                         24               9.1                     106
 5                         33               9.8                      96
 6                         23              NA                       109
 7                         25               8.8                     106
 8                         26               8.7                     102
 9                         23               9.4                     107
10                         20               7.4                      98
   valuenum_50912_Creatinine valuenum_50931_Glucose valuenum_50960_NA
                       &lt;dbl&gt;                  &lt;dbl&gt;             &lt;dbl&gt;
 1                       0.5                    115               2.3
 2                      NA                       NA              NA  
 3                       0.4                    113               1.9
 4                       0.8                    146               1.5
 5                       1.1                    148               2.2
 6                       1.1                     98               2.1
 7                       0.9                     95               2  
 8                       0.8                     88               2  
 9                       0.8                    127               1.6
10                       0.8                     99               1.4
   valuenum_50971_Potassium valuenum_50983_Sodium valuenum_51221_Hematocrit
                      &lt;dbl&gt;                 &lt;dbl&gt;                     &lt;dbl&gt;
 1                      4.7                   132                      NA  
 2                     NA                      NA                      NA  
 3                      3.6                   138                      33.6
 4                      3.9                   140                      39.1
 5                      4                     136                      36  
 6                      4                     140                      28.6
 7                      4.5                   139                      37.9
 8                      3.9                   138                      32.5
 9                      4.8                   142                      39.3
10                      3.9                   129                      28.7
   `valuenum_51301_White Blood Cells` charttime_220045    charttime_220179   
                                &lt;dbl&gt; &lt;dttm&gt;              &lt;dttm&gt;             
 1                               NA   2180-07-23 14:12:00 2180-07-23 14:11:00
 2                               NA   2189-06-27 08:56:00 2189-06-27 08:55:00
 3                               19   2157-11-20 19:19:00 2157-11-20 19:19:00
 4                               17   2110-04-11 15:54:00 2110-04-11 16:00:00
 5                               18.4 2131-01-11 04:22:00 2131-01-11 04:25:00
 6                               18.2 2160-05-18 14:07:00 2160-05-19 07:53:00
 7                                5.5 2129-08-04 13:45:00 2129-08-04 16:49:00
 8                               10.1 2158-01-15 08:15:00 2158-01-15 08:18:00
 9                                4.3 2112-11-30 23:43:00 2112-12-01 00:10:00
10                               22.4 2156-04-12 17:26:00 2156-04-12 17:27:00
   charttime_220181    charttime_220210    charttime_223761    valuenum_220045
   &lt;dttm&gt;              &lt;dttm&gt;              &lt;dttm&gt;                        &lt;dbl&gt;
 1 2180-07-23 14:11:00 2180-07-23 14:12:00 2180-07-23 17:00:00              91
 2 2189-06-27 08:55:00 2189-06-27 08:54:00 2189-06-27 09:07:00              77
 3 2157-11-20 19:19:00 2157-11-20 19:19:00 2157-11-20 19:31:00              86
 4 2110-04-11 16:00:00 2110-04-11 16:00:00 2110-04-11 20:32:00              55
 5 2131-01-11 04:25:00 2131-01-11 05:00:00 2131-01-12 20:00:00              38
 6 2160-05-19 07:53:00 2160-05-18 14:07:00 2160-05-19 08:00:00              80
 7 2129-08-04 16:49:00 2129-08-04 13:45:00 2129-08-04 14:00:00              68
 8 2158-01-15 08:18:00 2158-01-15 08:15:00 2158-01-15 12:00:00             100
 9 2112-12-01 00:10:00 2112-11-30 23:43:00 2112-11-30 23:31:00              72
10 2156-04-12 17:27:00 2156-04-12 17:26:00 2156-04-12 17:25:00             124
   valuenum_220179 valuenum_220181 valuenum_220210 valuenum_223761 age_hadm
             &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;    &lt;dbl&gt;
 1              84              56              24            98.7       52
 2             150              92              23            98         76
 3             151             104              18            98.5       55
 4              73              59              19            97.7       46
 5             180              46              10            98.1       77
 6             104              77              14            97.2       57
 7             126              78              18            95.9       81
 8             123              80              29            98.6       21
 9             129              85              14            97.9       77
10              87              53              25           103.        81
   thirty_day_mort
   &lt;chr&gt;          
 1 FALSE          
 2 FALSE          
 3 FALSE          
 4 FALSE          
 5 TRUE           
 6 FALSE          
 7 FALSE          
 8 FALSE          
 9 FALSE          
10 FALSE          
# … with 53,055 more rows</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mimic_icu_cohort<span class="sc">$</span>thirty_day_mort)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
FALSE  TRUE 
47853  5212 </code></pre>
</div>
</div>
</section>
<section id="q8.-exploratory-data-analysis-eda" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="q8.-exploratory-data-analysis-eda"><span class="header-section-number">8</span> Q8. Exploratory data analysis (EDA)</h2>
<p>Summarize following information using appropriate numerics or graphs.</p>
<ul>
<li><code>thirty_day_mort</code> vs demographic variables (ethnicity, language, insurance, marital_status, gender, age at hospital admission)</li>
</ul>
<p><strong>Solution:</strong> <code>thirty_day_mort</code> vs ethnicity : We can very clearly see the difference in mortlality rates for white patients. Such a huge difference is not present for the other ethnic groups.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> ethnicity, <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># numerical info</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(mimic_icu_cohort<span class="sc">$</span>ethnicity, </span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>                       mimic_icu_cohort<span class="sc">$</span>thirty_day_mort) ,<span class="dv">2</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               
                                FALSE TRUE
  AMERICAN INDIAN/ALASKA NATIVE  0.00 0.00
  ASIAN                          0.03 0.03
  BLACK/AFRICAN AMERICAN         0.09 0.07
  HISPANIC/LATINO                0.04 0.02
  OTHER                          0.05 0.04
  UNABLE TO OBTAIN               0.01 0.02
  UNKNOWN                        0.10 0.22
  WHITE                          0.68 0.59</code></pre>
</div>
</div>
<p><code>thirty_day_mort</code> vs language : Most of the patients speak english here</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> language, <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># numerical info</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(mimic_icu_cohort<span class="sc">$</span>language, </span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>                       mimic_icu_cohort<span class="sc">$</span>thirty_day_mort) ,<span class="dv">2</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
          FALSE TRUE
  ?        0.10 0.11
  ENGLISH  0.90 0.89</code></pre>
</div>
</div>
<p><code>thirty_day_mort</code> vs insurance : Most of the patients either have medicare or another type of insurance. And most of them have a stark difference in mortality rates.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> insurance, <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co"># numerical info</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(mimic_icu_cohort<span class="sc">$</span>insurance, </span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>                       mimic_icu_cohort<span class="sc">$</span>thirty_day_mort) ,<span class="dv">2</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
           FALSE TRUE
  Medicaid  0.07 0.06
  Medicare  0.42 0.53
  Other     0.51 0.41</code></pre>
</div>
</div>
<p><code>thirty_day_mort</code> vs marital_status : Most of the patients admitted in the hospital are married. A large proportion of those who would most probably die below 30 belong to the widowed category.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> marital_status, <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># numerical info</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(mimic_icu_cohort<span class="sc">$</span>marital_status, </span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>                       mimic_icu_cohort<span class="sc">$</span>thirty_day_mort) ,<span class="dv">2</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
           FALSE TRUE
  DIVORCED  0.08 0.07
  MARRIED   0.50 0.49
  SINGLE    0.30 0.24
  WIDOWED   0.13 0.20</code></pre>
</div>
</div>
<p><code>thirty_day_mort</code> vs gender : The statistics looks almost similar for male and female.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> gender, <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co"># numerical info</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(mimic_icu_cohort<span class="sc">$</span>gender, </span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a>                       mimic_icu_cohort<span class="sc">$</span>thirty_day_mort) ,<span class="dv">2</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    FALSE TRUE
  F  0.44 0.46
  M  0.56 0.54</code></pre>
</div>
</div>
<p><code>thirty_day_mort</code> vs age :</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> anchor_age, <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co"># numerical info</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(mimic_icu_cohort<span class="sc">$</span>anchor_age, </span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>                       mimic_icu_cohort<span class="sc">$</span>thirty_day_mort) ,<span class="dv">2</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    
     FALSE TRUE
  18  0.00 0.00
  19  0.00 0.00
  20  0.01 0.00
  21  0.00 0.00
  22  0.00 0.00
  23  0.01 0.00
  24  0.00 0.00
  25  0.00 0.00
  26  0.01 0.00
  27  0.00 0.00
  28  0.01 0.00
  29  0.01 0.00
  30  0.01 0.00
  31  0.00 0.00
  32  0.01 0.00
  33  0.01 0.00
  34  0.01 0.00
  35  0.01 0.00
  36  0.01 0.00
  37  0.01 0.00
  38  0.01 0.00
  39  0.01 0.00
  40  0.01 0.00
  41  0.01 0.00
  42  0.01 0.00
  43  0.01 0.00
  44  0.01 0.01
  45  0.01 0.00
  46  0.01 0.01
  47  0.01 0.01
  48  0.01 0.01
  49  0.01 0.01
  50  0.01 0.01
  51  0.01 0.01
  52  0.02 0.01
  53  0.02 0.01
  54  0.02 0.02
  55  0.02 0.01
  56  0.02 0.01
  57  0.02 0.01
  58  0.02 0.01
  59  0.02 0.02
  60  0.02 0.01
  61  0.02 0.02
  62  0.02 0.02
  63  0.02 0.02
  64  0.02 0.02
  65  0.02 0.02
  66  0.02 0.02
  67  0.02 0.02
  68  0.02 0.02
  69  0.02 0.02
  70  0.02 0.02
  71  0.02 0.02
  72  0.02 0.02
  73  0.02 0.03
  74  0.02 0.02
  75  0.02 0.03
  76  0.02 0.02
  77  0.02 0.02
  78  0.02 0.02
  79  0.02 0.03
  80  0.02 0.03
  81  0.02 0.03
  82  0.02 0.03
  83  0.02 0.02
  84  0.02 0.03
  85  0.02 0.02
  86  0.01 0.03
  87  0.01 0.02
  88  0.01 0.02
  89  0.01 0.02
  91  0.04 0.09</code></pre>
</div>
</div>
<ul>
<li><code>thirty_day_mort</code> vs first lab measurements</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> valuenum_50882_Bicarbonate, <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1796 rows containing non-finite values (`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> valuenum_50902_Chloride, <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1756 rows containing non-finite values (`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> valuenum_50912_Creatinine, </span>
<span id="cb118-5"><a href="#cb118-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1775 rows containing non-finite values (`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb120-4"><a href="#cb120-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> valuenum_50931_Glucose , </span>
<span id="cb120-5"><a href="#cb120-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1872 rows containing non-finite values (`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> valuenum_50971_Potassium, <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1782 rows containing non-finite values (`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> valuenum_50983_Sodium, <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1750 rows containing non-finite values (`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb126-3"><a href="#cb126-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> valuenum_51221_Hematocrit, <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2019 rows containing non-finite values (`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb128-4"><a href="#cb128-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="fu">ifelse</span>(<span class="st">`</span><span class="at">valuenum_51301_White Blood Cells</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">100</span>, </span>
<span id="cb128-5"><a href="#cb128-5" aria-hidden="true" tabindex="-1"></a>                 <span class="st">`</span><span class="at">valuenum_51301_White Blood Cells</span><span class="st">`</span>, <span class="cn">NA</span>), </span>
<span id="cb128-6"><a href="#cb128-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2206 rows containing non-finite values (`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><code>thirty_day_mort</code> vs first vital measurements</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> valuenum_220045, </span>
<span id="cb130-4"><a href="#cb130-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 16 rows containing non-finite values (`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb132-3"><a href="#cb132-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> valuenum_220179 , </span>
<span id="cb132-4"><a href="#cb132-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 684 rows containing non-finite values (`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb134-3"><a href="#cb134-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">ifelse</span>(valuenum_220181 <span class="sc">&lt;</span> <span class="dv">200</span>, valuenum_220181, <span class="cn">NA</span>), </span>
<span id="cb134-4"><a href="#cb134-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 714 rows containing non-finite values (`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb136-3"><a href="#cb136-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> valuenum_220210 , </span>
<span id="cb136-4"><a href="#cb136-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 62 rows containing non-finite values (`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb138-2"><a href="#cb138-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb138-3"><a href="#cb138-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> valuenum_223761,</span>
<span id="cb138-4"><a href="#cb138-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 956 rows containing non-finite values (`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><code>thirty_day_mort</code> vs first ICU unit</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mimic_icu_cohort) <span class="sc">+</span> </span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> first_careunit, <span class="at">fill =</span> thirty_day_mort))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw2_files/figure-html/unnamed-chunk-61-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(mimic_icu_cohort<span class="sc">$</span>first_careunit, </span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>                       mimic_icu_cohort<span class="sc">$</span>thirty_day_mort) ,<span class="dv">2</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                  
                                                   FALSE TRUE
  Cardiac Vascular Intensive Care Unit (CVICU)      0.19 0.05
  Coronary Care Unit (CCU)                          0.11 0.14
  Medical Intensive Care Unit (MICU)                0.18 0.27
  Medical/Surgical Intensive Care Unit (MICU/SICU)  0.16 0.20
  Neuro Intermediate                                0.03 0.01
  Neuro Stepdown                                    0.01 0.00
  Neuro Surgical Intensive Care Unit (Neuro SICU)   0.02 0.04
  Surgical Intensive Care Unit (SICU)               0.15 0.17
  Trauma SICU (TSICU)                               0.13 0.13</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>